HOSTNAME=radix
TIMEZONE=America/Los_Angeles
KEYMAP=us
LOCALE=en_US.UTF-8
DESKTOP=kde
LIBC=glibc
KERNEL=lts
GPU_DRIVER=auto
FILESYSTEM=ext4
SWAP_GIB=4
USERNAME=user
ADMIN=yes
ONLINE_INSTALL=yes
SERIAL_CONSOLE=no
